### ISSUE TITLE
cursor is blinking in macOS

### ISSUE THREAD

**Issue by avivelmakias1** [alpha2phi/modern-neovim#16]
Hi alpha, first of all i wanted to say that i really like your config and the tutorials your posting on medium.

so i've tried to clone and run your repo, but it seems that every second or so my cursor is blinking, even though it's not enabled in my terminals.
I've tried using iTerm2, kitty, or even the default terminal app, and in all of them when i enter a file the cursor starts to blink.
I've also noticed that it's not happening when I'm in the explorer or any other buffer.

it's only happening in your configuration as far as i know (i've tried using astrovim, nvchad and lvim)
do you know what might cause the issue and how to fix it?

**Comment by mengwangk** [comment]
This is fixed in the  latest update
