### ISSUE TITLE
Strange python highlighting and cosmetics

### ISSUE THREAD

**Issue by windowsrefund** [alpha2phi/modern-neovim#27]
Hello. Active medium reader here who is enjoying my time exploring your content. I'm hoping you might help me understand what I'm seeing when I work with some python code using a fresh install of this disto.
```
import requests

DEFAULT_URL = "https://xkcd.com/1906"

def get_url(url=DEFAULT_URL):
    return requests.get(url).status_code
```
When I place my cursor on the 'def' or 'return' key word, I see this odd highlight activity which I do not understand?

![Screenshot_2023-06-21_00-14-59](https://github.com/alpha2phi/modern-neovim/assets/512222/af59d984-3652-4c01-baaf-96d678bf3a75)

I can reproduce this with any color scheme so I tend to think this may be a feature I don't grok rather than a mere cosmetic.

Also, what's going on with the light bulb that we see to the left? I recall using [nvim-lightbulb](https://github.com/kosayoda/nvim-lightbulb) in a previous life but that plugin isn't installed here. The bulb follows my cursor from line to line so I'm guessing it behaves like the plugin I've mentioned which means it would be trying to tell me 1 or more code actions is available. Entertaining this idea, I do see ruff is offering 2 code actions:

[1] Ruff: Organize Imports
[2] Ruff: Fix all

However, neither option is actually doing anything and I'm sure you'd agree, there's nothing to "organize" to begin with. I'm guessing ruff is generating a false-positive which in turn spawns the bulb?

**Comment by mengwangk** [comment]
The highlight feature is from vim-matchup

The lightbulb comes from Lspsaga

The ruff lsp issue is fixed

**Comment by windowsrefund** [comment]
Thank you. Looks like the ruff no-op situation is being discussed [here](https://github.com/astral-sh/ruff-lsp/issues/91).
