### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by Sigthror** [alpha2phi/modern-neovim#3]
Hello. Trying to install it on macOS, and have an issue during `mnv` step.
What i did:
1. Clone this repo
2. Checkout to 01-init.lua branch
3. Run `source ./install.sh`
4. Run `mnv`

After all this i got an error:

> E5113: Error while calling lua chunk: ...entsev/.config/modern-neovim/nvim/lua/config/options.lua:4:
> stack traceback:
>         [C]: in function '__newindex'
>         ...entsev/.config/modern-neovim/nvim/lua/config/options.lua:4: in main chunk
>         [C]: in function 'require'
>         $HOME/.config/modern-neovim/nvim/init.lua:1: in main chunk

**Comment by mengwangk** [comment]
Are you using the latest version of Neovim?
