### ISSUE TITLE
[Bug] Issue when installing the config

### ISSUE THREAD

**Issue by bassamsdata** [alpha2phi/modern-neovim#6]
after doing exactly what the article said, then enter `mnv`, neovim detects an issue with the config files, then neovim starts with the vanilla setup.

It's the same issue of #3 but I saw that it's closed with no solution.

<img width="971" alt="Screen Shot 2023-01-27 at 11 44 09 PM" src="https://user-images.githubusercontent.com/105807570/215242602-84b13d28-1528-4ee3-9a83-b6f5a4aa1960.png">

My neovim version is: NVIM v0.8.2 (latest stable)
MacOS: 12.6
stow (GNU Stow) version 2.3.1

Thanks a lot, your articles helped me a lot.

**Comment by bassamsdata** [comment]
I commented out the option `vim.o.shortmess = "filnxtToOFWIcC"`
then I got this error:
<img width="849" alt="Screen Shot 2023-01-28 at 12 10 09 AM" src="https://user-images.githubusercontent.com/105807570/215243393-4f477a84-752e-48ee-b744-57c29c70dbe9.png">

After that, I commented out the `option: vim.opt.splitkeep = "screen"`

then neovim worked and installed the plugins without any issues.

tbh, I know the first one is for shortcuts (as I understand 🙂) but the second I don't know what does that mean 😵‍💫.

**Comment by hirogami** [comment]
I also encountered an error caused by 'vim.o.shortmess = "filnxtToOFWIcC" in NVIM 0.8.2, but I upgraded to version 0.9.0 (a development build) and the error is no longer present. You can download version 0.9.0 from this link: https://github.com/neovim/neovim/releases/tag/nightly

**Comment by mengwangk** [comment]
This configuration uses the nightly build. You can either comment on the lines or check for the version

E.g.

if vim.fn.has("nvim-0.9.0") == 1 then
....
end

**Comment by bassamsdata** [comment]
Thanks a lot for your your replies and help. I didn't expect to be built on neovim v9 but the issue has been solved.
